dist: xenial
language: python
python:
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - make
deploy:
  provider: pypi
  user: jacobi
  skip_existing: true
  on:
    branch: master
    tags: true
