dist: xenial
sudo: false
language: python
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
before_install:
  - sudo rm -f /etc/boto.cfg
install:
  - pip install tox pipenv
  - pipenv install
script: tox
deploy:
  provider: pypi
  user: jacobi
  skip_existing: true
  on:
    branch: master
    tags: true
  password:
    secure: cmGJerE74ddOd3WXFgOvb2hhFG8ohmkszuzEUoV4c65O1V0UkTIgul0xnRmKamyZbhx0py63yKo9fRyiPOmKOksp444MCMlJ/LaS1wfgfWEXjNRD0pxGfG6Do+NM+L25yEPv7VANTPpPXMEXy0dwf1DYv9EwLh/7p8mbsGhxM24vgxCLt30NFuOofnuYWg+fp3T5RExXInDDDf393932AV792bFJxv8XpUceThytzfgQh2pum43ZKemWRDk8tpAE9Qq0BL/KyNDkf83aV/ZxAomH+jT3EN1QMS1QdNKGVMx7kbXVn6nEzOG5/7h1EzGVcj08xrhLxZtUv/dD6IwX8LrE95egP9xT2JjUS2DKiS8nIW+Rmf0yPNtl+FjUjwqm5BNOzDye0czCLQiVuC1BPvhStw4QxPvbLFcZ0dEKCZPhX6F8vxoLa2belRgqr1FKFMyZVYuYJmGZru4/G4T8Pp3dClflK/TrYdLBA+Jtuwo8R3p3zy7VWwkPNfk+Xo2H9LRO5y7X9bToichTDmIfhOhxtNVhPyElyRdnIAmdYwLQS18FlrddtzCeNgrc8grN8R0rPBthI2d+z6K+IFMghka4NgFqGxUYUp6ZAwzWXcgqN+IUeS17XIM1z7wrMzg33njLiLUSWoZ8CN2czXKXefFcdd07n/dCk5yBFaV3Eb8=
